[wip] add ownership for unshared secrets and configmaps
openshift/service-ca-operator pull request #220
Opened 2023-09-15 19:34 UTC by deads2k

The openshift/api field will merge and be revendored here.

serving secrets and injected configmaps are not shared, we stomp all the keys.  Add the service-ca as the owner of these configmaps since we control the content.

2023-09-19 18:54 UTC, deads2k commented
now updated with vendored constant

2023-10-19 09:07 UTC, liouk requested changes

2023-10-26 20:16 UTC, deads2k commented on pkg/controller/servingcert/controller/secret_updating_controller.go
> +	if update {
I personally dislike it because you have to remember more state, but I will yield to the reviewer.

2023-10-27 07:51 UTC, liouk requested changes

2023-10-27 07:51 UTC, liouk commented on pkg/controller/cabundleinjector/configmap.go
> +		configMapCopy.Annotations[api.OwningJiraComponent] = api.OwningJiraComponent
Shouldn't it be `configMapCopy.Annotations[apiannotations.OpenShiftComponent]` instead?

2023-10-27 07:51 UTC, liouk commented on pkg/controller/servingcert/controller/secret_creating_controller.go
> +					api.OwningJiraComponent:   "service-ca",
I actually meant to replace `"service-ca"` with `api.OwningJiraComponent`:
```go
apiannotations.OpenShiftComponent: api.OwningJiraComponent,
```

2023-10-27 07:51 UTC, liouk commented on pkg/controller/servingcert/controller/secret_creating_controller.go
> +				api.OwningJiraComponent:        "service-ca",
```go
apiannotations.OpenShiftComponent: api.OwningJiraComponent,
```

2023-10-27 07:51 UTC, liouk commented on pkg/controller/servingcert/controller/secret_creating_controller.go
> +	secretCopy.Annotations[api.OwningJiraComponent] = api.OwningJiraComponent
Shouldn't it be `secretCopy.Annotations[apiannotations.OpenShiftComponent]` instead?

2023-10-27 07:51 UTC, liouk commented on pkg/controller/servingcert/controller/secret_creating_controller_test.go
> +				api.OwningJiraComponent:        api.OwningJiraComponent,
Wrong annotation name here as well; `apiannotations.OpenShiftComponent`. Several occurences in this file.

2023-10-27 07:51 UTC, liouk commented on pkg/controller/servingcert/controller/secret_updating_controller.go
> +		secretCopy.Annotations[api.OwningJiraComponent] = api.OwningJiraComponent
Shouldn't it be `secretCopy.Annotations[apiannotations.OpenShiftComponent]` instead?

2023-10-27 19:18 UTC, deads2k commented
huh, wonder if that's a flake or I broke it

/retest

2023-10-30 18:54 UTC, deads2k commented
installer failure 
/retest

2023-11-01 14:46 UTC, deads2k commented
install failures

/retest

2023-11-03 08:17 UTC, liouk commented
/lgtm

2023-11-03 13:23 UTC, merged